name: mujoco_workshop
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.12
  - scipy
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - tqdm
  - h5py
  - pytables
  - seaborn
  - ipywidgets
  - jupyter
  - jupyterlab
  - pip:
    - mujoco
    - mujoco-mjx