name: mujoco_workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.10,<3.11
  - defaults::scipy
  - defaults::numpy <2.0
  - defaults::pandas
  - defaults::matplotlib
  - defaults::ipykernel
  - defaults::tqdm
  - defaults::h5py
  - defaults::pytables
  - defaults::seaborn
  - defaults::ipywidgets
  - defaults::jupyter
  - defaults::jupyterlab
  - pip